day04/myapp/models.py
from myapp.extension import db

class News(db.Model):
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True
    )
    title = db.Column(
        db.String(20)
    )

day04/myapp/__init__.py
import os

from flask import Flask

from myapp import settings
from myapp.extension import init_ext
from myapp.settings import BASE_DIR
from myapp.views import init_blue


def create_app(env_name="debug"):
    static_path = os.path.join(BASE_DIR,"static")
    templates_path = os.path.join(BASE_DIR,"templates")
    app = Flask(__name__,
                static_folder=static_path,
                template_folder=templates_path
                )
    # 配置
    app.config.from_object(settings.config.get(env_name))
    # 初始化第三方插件
    init_ext(app)
    # 注册蓝图
    init_blue(app)
    return app

day04/myapp/views.py
from flask import Blueprint, render_template, request, abort, g, jsonify,json

from myapp.extension import cache
from .models import *

PER_PAGE = 3

blue = Blueprint("fl04", __name__)


def init_blue(app):
    app.register_blueprint(blue)


@blue.route("/news/")
# @cache.cached(timeout=50)   # 加了这个东西,页面点击后不能跳转
def get_news():
    print("进来了")
    page = request.args.get("page")
    page_obj = News.query.paginate(int(page), PER_PAGE, False)
    return render_template("news.html", pagination=page_obj)


@blue.route("/newscache/")
def get_news_cache():
    # 拿客户端ip
    key = request.remote_addr + "cache"
    res = cache.get(key)
    if res:
        return res
    else:
        print("进来了")
        print(g.id)
        page = request.args.get("page")
        page_obj = News.query.paginate(int(page), PER_PAGE, False)
        html =  render_template("news.html", pagination=page_obj)
        # 把页面设置到缓存
        cache.set(key,html,20)
        return html

@blue.route("/score/")
def get_score():
    data = {
        "code":1,
        "msg":"ok",
        "data":[59,59,60,61,90,85]
    }
    # 转的是字符串,前端需要转成json
    # return json.dumps(data)
    # 转的是整个数据结构
    return jsonify(data)

@blue.before_request
def fanpa():
    # 拿ip
    addr = request.remote_addr
    agent = request.user_agent
    print(agent)
    g.id = addr
    if agent:
        pass
    else:
        return "你是垃圾爬虫师",500
    key = addr + "spider"
    tmp = cache.get(key)
    if tmp:
        if int(tmp) >= 20:
            return "搞你M啊",500
        else:
            cache.set(key,int(tmp) + 1,5)
    else:
        cache.set(key,1,5)
    print("爬虫处理")

day04/templates/news.html
{% extends "bootstrap/base.html" %}

{% block navbar %}
    <div class="container">
        <nav class="navbar navbar-inverse">
            {#        <div class="container-fluid">#}
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="#">商品管理</a></li>
                    <li><a href="#">订单管理</a></li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="搜索商品">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">登录</a></li>
                    <li><a href="#">注册</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
            {#        </div><!-- /.container-fluid -->#}
        </nav>
    </div>

{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>欢迎来到英雄联盟</h1>
            <p>一段操作猛如虎 原来是二百五</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">了解更多</a></p>
        </div>
        <div>
            <h3>接下来是今日新闻</h3>
        </div>
        {#    新闻数据#}
        <ol>
            {% for i in pagination.items %}
                <li>{{ i.title }}</li>
            {% else %}
                <h6>小编被开了</h6>
            {% endfor %}

        </ol>
        {#        分页#}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    {#                如果有前一页，则是前一夜的页码，没有就是一#}
                    {% if pagination.has_prev %}
                        <a href="{{ url_for('fl04.get_news') }}?page={{ pagination.prev_num }}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                    {% else %}
                        <a href="{{ url_for('fl04.get_news') }}?page=1" aria-label="Previous">
                            <span aria-hidden="true">首页</span>
                        </a>
                    {% endif %}
                </li>

                {#            循环生成页码#}
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        {% if page == pagination.page %}
                            <li class="active">
                                <a href="{{ url_for('fl04.get_news') }}?page={{ page }}">{{ page }}</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{{ url_for('fl04.get_news') }}?page={{ page }}">{{ page }}</a>
                            </li>
                        {% endif %}
                    {% else %}
                        <span class=ellipsis>我是一个有底线的人</span>
                    {% endif %}
                {% endfor %}

{#                判断有没有后一页#}
                <li>
                    {% if pagination.has_next %}
                        <a href="{{ url_for('fl04.get_news') }}?page={{ pagination.next_num }}" aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                        </a>
                    {% else %}
                        <a href="{{ url_for('fl04.get_news') }}?page={{ pagination.pages }}" aria-label="Next">
                            <span aria-hidden="true">尾页</span>
                        </a>
                    {% endif %}
                </li>

            </ul>
        </nav>
    </div>
{% endblock %}